### ISSUE TITLE
Finalisierung Ausarbeitung Versuch2

### ISSUE THREAD

**Issue by peterfoerster** [peterfoerster/VAdF#1]
Finalisieren des Dokuments zu Versuch2

**Comment by Mosarvit** [comment]
Alle Korrekturen konnte ich ausbessern, bis auf die letzte. 

Ich weiss nicht genau, wie ich ihre Alternativlösung beschreiben soll, da ich sie so ganz verstehe. 
Wäre also schön, wenn stattdessen einer von euch beiden das tut und später mir die Lösung erklärt. 

![new doc 2018-05-10](https://user-images.githubusercontent.com/10900709/39845331-7afe7c68-53f5-11e8-8af5-dd7553c620b5.jpg)

**Comment by JayJay0815** [comment]
schaue sie mir an, dann können wir morgen nochmal drüber schauen, falls ich auch keine Idee habe.

**Comment by peterfoerster** [comment]
das meinte sie nur als hinweis, wenn ich mich recht entsinne
also das war keine aufforderung, dass wir das auch noch zeigen sollten
die wahl von hz außerhalb des gitters wüsste ich sonst auch, nur für die virtuelle spiegelladung in FIT wäre ich planlos

**Comment by JayJay0815** [comment]
hz außerhalb könnte ich mir auch noch vorstellen - aber ich komme momentan auch auf keine sinnvolle Idee. Also vor allem, wie das sich im Gitter (und nicht in den Feldwerten) darstellen soll.

**Comment by peterfoerster** [comment]
ich denke wir können das auch noch gar nicht richtig verstehen, weil in der vorlesung ja noch nicht erklärt wurde, wie wir raumladungen überhaupt dem gitter zuweisen
das kommt später zusammen mit der E-Statik bestimmt noch, aber bis jetzt habe ich zumindest das noch nicht mitbekommen

**Comment by JayJay0815** [comment]
Dann schließen wir dieses Issue und lassen das jetzt so, ja?
