### ISSUE TITLE
Finalisierte Ausarbeitung Versuch 2 korrekturlesen

### ISSUE THREAD

**Issue by Mosarvit** [peterfoerster/VAdF#27]
Ich hab dich, Jonas, wie abgesprochen, dafür eingeschrieben. Sobald du soweit bist, kannst du die gerne direkt abschicken.

**Comment by JayJay0815** [comment]
Nichts hinzuzufügen, super :)

**Comment by JayJay0815** [comment]
- noch nicht hochgeladen, muss zusammen mit Ausarbeitung zu V3 hochgeladen werden
