### ISSUE TITLE
Versuch 6 Vorbereitungsaufgabe 3 - Ergänzung

### ISSUE THREAD

**Issue by Mosarvit** [peterfoerster/VAdF#37]

**Comment by JayJay0815** [comment]
Geschlossen mit Jonas13

**Comment by JayJay0815** [comment]
Grooooßes Fragezeichen bei der Bearbeitung:
- warum schätzen wir \Delta t_max mit \lambda_max ab, wenn doch für \lambda_min^-1 > \lambda_max^-1 gilt? Müssten wir also nicht eher \lambda_min abschätzen??? Sowohl i. d. Skript als auch in der Aufgabe? Genauso für A5?

**Comment by JayJay0815** [comment]
Habe mich jetzt länger als sinnvoll mit den Plots dieser Zeitgraphen auseinander gesetzt - könntest du @Mosarvit die über dein EPS-Tool darstellen? 
- Mein Problem ist, dass ich versucht habe über Geogebra und Export in Tikz das darzustellen, aber noch zuviele Fehler habe, als dass sich das meiner Meinung nach im Moment lohnt, wenn du da schneller bist.
Darstellungen sind folgende:
![grafik](https://user-images.githubusercontent.com/38729625/40886578-d94cb07a-673a-11e8-9c2d-939be3bba4d5.png)
![grafik](https://user-images.githubusercontent.com/38729625/40886607-8d1c29a0-673b-11e8-93b2-15d07c51c2ef.png)
![grafik](https://user-images.githubusercontent.com/38729625/40886626-e7f6b0d4-673b-11e8-959b-807691895344.png)

**Comment by Mosarvit** [comment]
mache ich, geht klar

**Comment by JayJay0815** [comment]
Könntest du @Mosarvit ggf noch zwei kleine Anpassungen an den Bildern vornehmen?
ist es möglich, die e_fit und b_fit mit den Darstellungen aus Latex als \efit und \bfit, also mit den bögen drüber, darszustellen?
können wir noch Pfeilspitzen mit der Beschriftung "Zeitschritte" auf den nach links laufenden Linien einsetzen, etwa so:

![grafik](https://user-images.githubusercontent.com/38729625/41201406-acf6d802-6cb7-11e8-9982-52b36c220e7d.png)
