### ISSUE TITLE
Versuch 4 Finalisierung Vorbereitung Aufg 4

### ISSUE THREAD

**Issue by JayJay0815** [peterfoerster/VAdF#53]
Kommentar von Laura zur Ausarbeitung der V4 Vb Aufg 4:
zur Grafik des Differenzenstern: "Was soll damit ausgedrückt werden" da Linien verschoben wurden und nicht wie gedacht als dreidimensionale Darstellung verstanden werden konnten 
-> gewünscht:
- Kurze Nachbesserung Grafik & Bezug, was gezeigt wird
- Ergänzung zur Erklärung der Potentialwerte, welches Rechengebiet genutzt wurde

Assigning @Mosarvit , da hoffentlich einfacher, sich nochmal in die von einem selbst bearbeiteten Aufgaben einzudenken

**Comment by Mosarvit** [comment]
Die graphik ist jetzt nachgebessert.

bzgl. "Ergänzung zur Erklärung der Potentialwerte, welches Rechengebiet genutzt wurde", weiss ich nicht was gemeint ist. Dort steht "[...]  sollen nun die Potentiale an den Randpunkten des Gitters [...] ". 
Sollen die Potential in das Gitter miteingezeichnet werden?

**Comment by JayJay0815** [comment]
War nicht so kompliziert gedacht meiner Meinung. Habe das jetzt nachgebessert. 
Damit müsste meiner Meinung nach dieser Issue erledigt sein
