### ISSUE TITLE
Finalisierung Versuch 5

### ISSUE THREAD

**Issue by JayJay0815** [peterfoerster/VAdF#54]

**Comment by JayJay0815** [comment]
Wir lassen die Ausarbeitung von Versuch 5 dann auf dem Stand, auf dem wir laut Diskussion am Montag noch einige Fehler haben, ja? Und warten dann auf Korrektur / Tipps von Laura?

**Comment by peterfoerster** [comment]
Genau, dass ist jetzt mein Plan. Ich sehe den Fehler da leider nicht.
